language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

before_script:
  - npm install -g firebase-tools
  - npm install

script:
  - npm run build

after_success:
  - firebase deploy --token $firebase_token --non-interactive